### ISSUE TITLE
Error at static mesh export

### ISSUE THREAD

**Issue by kpulka** [xavier150/Blender-For-UnrealEngine-Addons#106]
I'm having a problem with export certain meshes. I tried UV cleanup, merging object to a box to clean the mesh.

Traceback (most recent call last):
  File "C:\Users\kpulka\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2401, in execute
    bfu_export_asset.ExportForUnrealEngine()
  File "C:\Users\kpulka\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 323, in ExportForUnrealEngine
    targetcollection=col_list,
  File "C:\Users\kpulka\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 196, in ExportAllAssetByList
    ProcessStaticMeshExport(obj)
  File "C:\Users\kpulka\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-for-unrealengine\bfu_export_single_static_mesh.py", line 56, in ProcessStaticMeshExport
    ExportSingleStaticMesh(dirpath, GetObjExportFileName(obj), obj)
  File "C:\Users\kpulka\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-for-unrealengine\bfu_export_single_static_mesh.py", line 139, in ExportSingleStaticMesh
    bake_space_transform=False
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\__init__.py", line 636, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3094, in save_single
    fbx_objects_elements(root, scene_data)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2894, in fbx_objects_elements
    fbx_data_mesh_elements(objects, me_obj, scene_data, done_meshes)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 1174, in fbx_data_mesh_elements
    elem_data_single_int32_array(lay_uv, b"UVIndex", (uv2idx[uv_id] for uv_id in _uvtuples_gen(t_luv, t_lvidx)))
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\fbx_utils.py", line 504, in elem_data_single_int32_array
    return _elem_data_single(elem, name, value, "add_int32_array")
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\fbx_utils.py", line 451, in _elem_data_single
    getattr(sub_elem, func_name)(value)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\encode_bin.py", line 161, in add_int32_array
    data = array.array(data_types.ARRAY_INT32, data)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 1174, in <genexpr>
    elem_data_single_int32_array(lay_uv, b"UVIndex", (uv2idx[uv_id] for uv_id in _uvtuples_gen(t_luv, t_lvidx)))
KeyError: ((nan, 58.36199188232422), 2942)

location: C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

**Comment by xavier150** [comment]
That look like an error from Blender, io_scene_fbx. You can send me the file ?
Xavierloux.loux@gmail.com if the file is private

**Comment by xavier150** [comment]
You still have issues? I not received file.
If not you can close this issue. :)

**Comment by deepak02717** [comment]
same here.....i also tried with the simple scene that include blender default cube and camera.....and keyframe the camera for a simple animation scene.....and done the same as shown in tutorial....but as i hit on export showing bunch of similar errors...

**Comment by xavier150** [comment]
Hey @deepak02717,

Exacly the same error? This look like a error from io_scene_fbx in Blender not my Addon. You can send me the file? I will try to reproduce on my side to know what wrong and set up a workaround.

**Comment by mirh** [comment]
As a matter of fact, the io_export_psk_psa addon recently fixed a bug about static meshes without armature modifiers.

**Comment by xavier150** [comment]
> As a matter of fact, the io_export_psk_psa addon recently fixed a bug about static meshes without armature modifiers.

I will look about, thanks

**Comment by xavier150** [comment]
I close this for te moment, I need know how reproduce
