### ISSUE TITLE
Can't Export Camera out of Blender 2.8 Getting the following error

### ISSUE THREAD

**Issue by flyinglime012** [xavier150/Blender-For-UnrealEngine-Addons#111]
When trying to export out of blender I got this error. I tried it again with a fresh scene and got the same issue. 

Traceback (most recent call last):
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2401, in execute
    bfu_export_asset.ExportForUnrealEngine()
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 339, in ExportForUnrealEngine
    targetcollection=col_list,
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 195, in ExportAllAssetByList
    ProcessCameraExport(obj)
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_export_single_camera.py", line 73, in ProcessCameraExport
    obj
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_export_utils.py", line 457, in ExportSingleAdditionalTrackCamera
    AdditionalTrack = bfu_write_text.WriteCameraAnimationTracks(obj)
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_write_text.py", line 422, in WriteCameraAnimationTracks
    camera_tracks.EvaluateTracks(obj, scene.frame_start, scene.frame_end)
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_write_text.py", line 394, in EvaluateTracks
    marker_sequence = slms.GetMarkerSequenceAtFrame(frame)
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_utils.py", line 431, in GetMarkerSequenceAtFrame
    for marker_sequence in self.marker_sequences:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

**Comment by xavier150** [comment]
Hey @flyinglime012 
Thanks for the report! 
I updated the dev branch, you can check if that work better? [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)

**Comment by flyinglime012** [comment]
Really appreciate your attention on this, I downloaded the dev branch version and deleted the other version, but unfortunately I'm still getting the error. I don't think it's any different but I'll resend. I've tried with a brand new scene, tried exporting camera and mesh but same error.

Traceback (most recent call last):
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2401, in execute
    bfu_export_asset.ExportForUnrealEngine()
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 339, in ExportForUnrealEngine
    targetcollection=col_list,
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 195, in ExportAllAssetByList
    ProcessCameraExport(obj)
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_export_single_camera.py", line 73, in ProcessCameraExport
    obj
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_export_utils.py", line 457, in ExportSingleAdditionalTrackCamera
    AdditionalTrack = bfu_write_text.WriteCameraAnimationTracks(obj)
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_write_text.py", line 422, in WriteCameraAnimationTracks
    camera_tracks.EvaluateTracks(obj, scene.frame_start, scene.frame_end)
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_write_text.py", line 394, in EvaluateTracks
    marker_sequence = slms.GetMarkerSequenceAtFrame(frame)
  File "C:\Users\aspen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_utils.py", line 431, in GetMarkerSequenceAtFrame
    for marker_sequence in self.marker_sequences:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

**Comment by xavier150** [comment]
I'm sorry that an error from my part, I updated the dev branch, you can try again ?

**Comment by flyinglime012** [comment]
It's working now, thanks Xavier!
