### ISSUE TITLE
No Animation keys in UE5

### ISSUE THREAD

**Issue by TheBeatBang** [xavier150/Blender-For-UnrealEngine-Addons#113]
Hello Xavier,

Thanks for your work,

I'm on Blender 2.92 and UE5. I did activate plugins in UE5. The script opens the sequencer in UE but there are no animation keys on the camera transforms.

Here is the Blender info log when I click on "Export for "Unreal Engine 4" : 

Python: Traceback (most recent call last):
  File "C:\Users\Sarcive\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2401, in execute
    bfu_export_asset.ExportForUnrealEngine()
  File "C:\Users\Sarcive\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 339, in ExportForUnrealEngine
    targetcollection=col_list,
  File "C:\Users\Sarcive\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 195, in ExportAllAssetByList
    ProcessCameraExport(obj)
  File "C:\Users\Sarcive\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_export_single_camera.py", line 73, in ProcessCameraExport
    obj
  File "C:\Users\Sarcive\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_export_utils.py", line 457, in ExportSingleAdditionalTrackCamera
    AdditionalTrack = bfu_write_text.WriteCameraAnimationTracks(obj)
  File "C:\Users\Sarcive\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_write_text.py", line 422, in WriteCameraAnimationTracks
    camera_tracks.EvaluateTracks(obj, scene.frame_start, scene.frame_end)
  File "C:\Users\Sarcive\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_write_text.py", line 394, in EvaluateTracks
    marker_sequence = slms.GetMarkerSequenceAtFrame(frame)
  File "C:\Users\Sarcive\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_utils.py", line 431, in GetMarkerSequenceAtFrame
    for marker_sequence in self.marker_sequences:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

Let me know,
Thanks
Romain

**Comment by xavier150** [comment]
Hey @TheBeatBang,
Sorry for that, this bug was product when the scene has no Markers in Timeline. [Blender Markers](https://docs.blender.org/manual/en/latest/animation/markers.html) I Fixed this error in the Dev Branch

You can add Markers or use the last Dev Branch [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons)

**Comment by thesolidice** [comment]
Hi Xavier, I have this exact same problem in UE4.25 using the dev branch and after placing markers. 

When checking the sequencer json file, this is all there is:

{
    "Coment": {
        "1/3": "This file was generated with the addons Blender for UnrealEngine : https://github.com/xavier150/Blender-For-UnrealEngine-Addons",
        "2/3": "This file contains additional Camera animation informations that is not supported with .fbx files",
        "3/3": "The script must be used in Unreal Engine Editor with Python plugins : https://docs.unrealengine.com/en-US/Engine/Editor/ScriptingAndAutomation/Python"
    },
    "Frames": [
        {
            "frame_start": 1,
            "frame_end": 92
        }
    ],
    "Camera transform": {},
    "Camera FocalLength": {},
    "Camera SensorWidth": {},
    "Camera SensorHeight": {},
    "Camera FocusDistance": {},
    "Camera Aperture": {},
    "Camera Spawned": {}
}

**Comment by xavier150** [comment]
Hey @thesolidice, 
Thanks for the report. Looks like the camera can't find any information.
You can send me the file? xavierloux.loux@gmail.com I will try to reproduct on my side. Btw you use what version of Blender?

**Comment by xavier150** [comment]
Hey @thesolidice,
Thanks for the file. I reproduce the issue I found why that don't work. Recently I made an optimization to calculate only the keys visible in the camera cut which caused this issue. I fixed and updated the Dev Branch: [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)

**Comment by TheBeatBang** [comment]
Hi Xavier,
I Xavier, thanks for your quick support, the markers work just fine by my side.
Such handy tool.
R.
