### ISSUE TITLE
Export problem

### ISSUE THREAD

**Issue by Alan3210** [xavier150/Blender-For-UnrealEngine-Addons#14]
Hello.
Version: 2.8.

When pressing the button "Export for Unreal Engine" (exporting just a monkey head) error reports:

Traceback (most recent call last):
  File "C:\Users\asche\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\__init__.py", line 1150, in execute
    bfu_exportasset.ExportForUnrealEngine()
  File "C:\Users\asche\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\bfu_exportasset.py", line 460, in ExportForUnrealEngine
    PrepareAndSaveDataForExport()
  File "C:\Users\asche\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\bfu_exportasset.py", line 432, in PrepareAndSaveDataForExport
    ExportAllAssetByList(GetAllobjectsByExportType("export_recursive"))
  File "C:\Users\asche\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\bfu_exportasset.py", line 344, in ExportAllAssetByList
    ExportSingleFbxMesh(GetObjExportDir(obj), GetObjExportFileName(obj), obj)
  File "C:\Users\asche\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\bfu_exportasset.py", line 185, in ExportSingleFbxMesh
    absdirpath = bpy.path.abspath(dirpath)
  File "C:\blender-2.80.0-git.427c75e4c20b-windows64\2.80\scripts\modules\bpy\path.py", line 88, in abspath
    if start is None else start,
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 24: invalid continuation byte

location: <unknown location>:-1
---------------------

Any ideas?

**Comment by Alan3210** [comment]
Solved.
