### ISSUE TITLE
Python: Traceback (most recent call last):

### ISSUE THREAD

**Issue by KOPBYC** [xavier150/Blender-For-UnrealEngine-Addons#147]
Python: Traceback (most recent call last):
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\error.py", line 246, in execute
    self.run(context)
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\daz.py", line 47, in run
    getMainAsset(self.filepath, context, self)
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\main.py", line 87, in getMainAsset
    asset.build(context)
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\cycles.py", line 70, in build
    self.tree.build()
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\cycles.py", line 285, in build
    self.buildLayer()
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\cycles.py", line 318, in buildLayer
    self.buildBumpNodes()
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\cycles.py", line 420, in buildBumpNodes
    tex = self.addTexImageNode(channel, "NONE")
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\cycles.py", line 1216, in addTexImageNode
    texnode,isnew = self.addSingleTexture(col, assets[0], maps[0], colorSpace)
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\cycles.py", line 1147, in addSingleTexture
    img = asset.buildCycles(colorSpace)
  File "C:\Users\Ruslan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\import_daz\material.py", line 759, in buildCycles
    img.colorspace_settings.name = "Non-Color"
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ('Linear', 'sRGB')

location: <unknown location>:-1

Я пытался через аддон "daz importer 1.5" импортировать  сцену в Blender. Но выходит ошибка. Все возможные пути выставил но без изменений. 
_______________________________________________________
I tried using the addon "dayz importer 1.5" to import a scene into Blender. But an error comes out. I have set all possible paths, but without changes.

**Comment by xavier150** [comment]
Hello! 
I don't have control on dayz importer 1.5. You sould contact the owner of dayz importer addon.
