### ISSUE TITLE
VertexColor

### ISSUE THREAD

**Issue by pierresigwalt** [xavier150/Blender-For-UnrealEngine-Addons#158]
Hi,

I was trying to export a skeletal mesh for Unreal and came accross the following error:

Python: Traceback (most recent call last):
  File "C:\Users\sigwa\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2449, in execute
    bfu_export_asset.ExportForUnrealEngine()
  File "C:\Users\sigwa\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blender-for-unrealengine\export\bfu_export_asset.py", line 331, in ExportForUnrealEngine
    ExportAllAssetByList(
  File "C:\Users\sigwa\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blender-for-unrealengine\export\bfu_export_asset.py", line 217, in ExportAllAssetByList
    ProcessSkeletalMeshExport(obj)
  File "C:\Users\sigwa\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blender-for-unrealengine\export\bfu_export_single_skeletal_mesh.py", line 59, in ProcessSkeletalMeshExport
    ExportSingleSkeletalMesh(scene, dirpath, GetObjExportFileName(obj), obj)
  File "C:\Users\sigwa\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blender-for-unrealengine\export\bfu_export_single_skeletal_mesh.py", line 141, in ExportSingleSkeletalMesh
    SetVertexColorForUnrealExport(active)
  File "C:\Users\sigwa\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\blender-for-unrealengine\export\bfu_export_utils.py", line 371, in SetVertexColorForUnrealExport
    new_vertex_color.name = "BFU_VertexColorExportName"
AttributeError: 'NoneType' object has no attribute 'name'

1. I have parented the mesh to the armature
2. Setup some Color Attribute (for MAP ID in substance painter)
3. Setup some Weight for the animation
4. Click on Export for Unreal using SkeletalMesh Option
5. Error show

![Capture](https://user-images.githubusercontent.com/8101858/182015448-45e7b742-cce8-4f34-a68b-966fec91b7ff.PNG)

Thank you!

**Comment by xavier150** [comment]
Hello, I'm sorry for the long delay. 
I updated the dev branch. That should be fixed now. 
You can try it? -> https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

**Comment by xavier150** [comment]
Hello again. I updated the addon.
Check in releases: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases
