### ISSUE TITLE
TypeError: user_resource() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by gerroon** [xavier150/Blender-For-UnrealEngine-Addons#188]
Hi

I am getting this error on Windows 11, Blender 4.2, 0.2.9

```

Export assets: [--------------------] 0.0%
FBX export starting... 'P:\\ExportedFbx\\StaticMesh\\Export\\SM_Suzanne.fbx'
export finished in 0.0000 sec.
Export assets: [####################] 100.0% DONE
Export assets: [####################] 100.0% DONE IN 0.01s
File type not found in this assets: ABC
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2283, in execute
    bfu_write_text.WriteAllTextFiles()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender-for-unrealengine\bfu_write_text.py", line 504, in WriteAllTextFiles
    source = os.path.join(bpy.utils.user_resource('SCRIPTS', os.path.join("addons", "blender-for-unrealengine", "import")), "asset_import_script.py")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: user_resource() takes 1 positional argument but 2 were given
Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2283, in execute
    bfu_write_text.WriteAllTextFiles()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender-for-unrealengine\bfu_write_text.py", line 504, in WriteAllTextFiles
    source = os.path.join(bpy.utils.user_resource('SCRIPTS', os.path.join("addons", "blender-for-unrealengine", "import")), "asset_import_script.py")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: user_resource() takes 1 positional argument but 2 were given


```

**Comment by xavier150** [comment]
Hello! I checking the old issues on github.
You still have this issue? if yes you can send me the blend file ?
