### ISSUE TITLE
Error with newest release

### ISSUE THREAD

**Issue by CodeDoes** [xavier150/Blender-For-UnrealEngine-Addons#36]
```
...
export finished in 0.7031 sec.
Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\__init__.py", line 1504, in execute
    bfu_ExportAsset.ExportForUnrealEngine()
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 550, in ExportForUnrealEngine
    PrepareAndSaveDataForExport()
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 537, in PrepareAndSaveDataForExport
    targetActionName = baseActionName,
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 485, in ExportAllAssetByList
    ExportSingleFbxAction(originalScene, animExportDir, GetActionExportFileName(obj, action), obj, action, "Pose")
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 104, in ExportSingleFbxAction
    obj.location = originalLoc #Resets previous object location
NameError: name 'originalLoc' is not defined
```

**Comment by xavier150** [comment]
Hello CodeDoes,
Thanks for the report ! It should work now: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v.0.2.4c

**Comment by CodeDoes** [comment]
Thanks, it works now. :)
