### ISSUE TITLE
FBX Camera Fails to export

### ISSUE THREAD

**Issue by csvfx** [xavier150/Blender-For-UnrealEngine-Addons#55]
Great tool!

But I have issues with FBX cameras i'm exported from Nuke.

When i try and export the camera, i get this error

Traceback (most recent call last):
  File "C:\Users\cam\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\__init__.py", line 1696, in execute
    bfu_ExportAsset.ExportForUnrealEngine()
  File "C:\Users\cam\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 194, in ExportForUnrealEngine
    PrepareAndSaveDataForExport()
  File "C:\Users\cam\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 182, in PrepareAndSaveDataForExport
    targetcollection = baseCollectionName,
  File "C:\Users\cam\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 76, in ExportAllAssetByList
    ExportSingleFbxCamera(originalScene, GetObjExportDir(obj), GetObjExportFileName(obj), obj)
  File "C:\Users\cam\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-for-unrealengine\bfu_ExportAssetsByType.py", line 639, in ExportSingleFbxCamera
    scene.frame_start = GetDesiredActionStartEndTime(obj, action)[0]
TypeError: 'NoneType' object is not subscriptable

location: <unknown location>:-1

Any ideas what might be up? I've included the camera.fbx and the blend file i've tried exporting from.

The same camera imported as an alembic will export fine, but that's not an ideal workflow either.

[camera_and_blend.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4637128/camera_and_blend.zip)

**Comment by xavier150** [comment]
Hey csvfx!

Thanks for the feedback! This error was corrected in v2.7 you can already download it from the source code: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/tree/master/blender-for-unrealengine%20-%202.8

Or wait the 0.2.7 release. I will publish I think tomorrow!

**Comment by xavier150** [comment]
Hey csvfx,
That published, you can download the new version here: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.7

**Comment by csvfx** [comment]
Thanks :-)
