### ISSUE TITLE
Problem at Check for potential errors

### ISSUE THREAD

**Issue by talesrt** [xavier150/Blender-For-UnrealEngine-Addons#67]
Hello,

eveytime I try to check for potential errors I've got that problem output:

`Traceback (most recent call last):
  File "C:\Users\tales\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-for-unrealengine\__init__.py", line 1689, in invoke
    UpdateUnrealPotentialError()
  File "C:\Users\tales\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-for-unrealengine\bfu_Utils.py", line 1200, in UpdateUnrealPotentialError
    CheckVertexGroupWeight()
  File "C:\Users\tales\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-for-unrealengine\bfu_Utils.py", line 1163, in CheckVertexGroupWeight
    VertexWithZeroWeight = GetVertexWithZeroWeight(obj, child)
  File "C:\Users\tales\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-for-unrealengine\bfu_Utils.py", line 913, in GetVertexWithZeroWeight
    if Mesh.vertex_groups[GroupElem.group].name in Armature.data.bones:
IndexError: bpy_prop_collection[index]: index 68 out of range, size 0

location: <unknown location>:-1

`

**Comment by xavier150** [comment]
Hello!
I'm sorry I never saw your message notification. You still have the problem?
If you still have the problem maybe you can send me the file I will try to reproduce on my side.
