### ISSUE TITLE
Error after clicking Export to Unreal (Blender 2.83)

### ISSUE THREAD

**Issue by HeyNinety** [xavier150/Blender-For-UnrealEngine-Addons#69]
![image](https://user-images.githubusercontent.com/68526679/87898243-463fd800-ca13-11ea-938d-94eb080d01cf.png)

~

Traceback (most recent call last):
  File "C:\Users\heyni\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-for-unrealengine\__init__.py", line 1789, in execute
    bfu_ExportAsset.ExportForUnrealEngine()
  File "C:\Users\heyni\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 226, in ExportForUnrealEngine
    PrepareAndSaveDataForExport()
  File "C:\Users\heyni\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 202, in PrepareAndSaveDataForExport
    targetcollection = baseCollectionName,
  File "C:\Users\heyni\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 85, in ExportAllAssetByList
    ExportSingleStaticMesh(originalScene, GetObjExportDir(obj), GetObjExportFileName(obj), obj)
  File "C:\Users\heyni\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-for-unrealengine\bfu_ExportAssetsByType.py", line 579, in ExportSingleStaticMesh
    bake_space_transform = False
  File "E:\Programs\Blender\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "E:\Programs\Blender\2.83\scripts\addons\io_scene_fbx\__init__.py", line 634, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "E:\Programs\Blender\2.83\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "E:\Programs\Blender\2.83\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3094, in save_single
    fbx_objects_elements(root, scene_data)
  File "E:\Programs\Blender\2.83\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2894, in fbx_objects_elements
    fbx_data_mesh_elements(objects, me_obj, scene_data, done_meshes)
  File "E:\Programs\Blender\2.83\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 1174, in fbx_data_mesh_elements
    elem_data_single_int32_array(lay_uv, b"UVIndex", (uv2idx[uv_id] for uv_id in _uvtuples_gen(t_luv, t_lvidx)))
  File "E:\Programs\Blender\2.83\scripts\addons\io_scene_fbx\fbx_utils.py", line 504, in elem_data_single_int32_array
    return _elem_data_single(elem, name, value, "add_int32_array")
  File "E:\Programs\Blender\2.83\scripts\addons\io_scene_fbx\fbx_utils.py", line 451, in _elem_data_single
    getattr(sub_elem, func_name)(value)
  File "E:\Programs\Blender\2.83\scripts\addons\io_scene_fbx\encode_bin.py", line 161, in add_int32_array
    data = array.array(data_types.ARRAY_INT32, data)
  File "E:\Programs\Blender\2.83\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 1174, in <genexpr>
    elem_data_single_int32_array(lay_uv, b"UVIndex", (uv2idx[uv_id] for uv_id in _uvtuples_gen(t_luv, t_lvidx)))
KeyError: ((nan, nan), 1743)

location: E:\Programs\Blender\2.83\scripts\modules\bpy\ops.py:201

location: <unknown location>:-1

~ Tried with Blender 2.82 and 2.81 and still got a similar Traceback Error.

**Comment by xavier150** [comment]
Hello HeyNinety,

Oh that seem come from the FBX export addon. You can send me the file? I
will try to find what is wrong to correct in the next update.

Le lun. 20 juil. 2020 à 06:01, HeyNinety <notifications@github.com> a
écrit :

**Comment by HeyNinety** [comment]
So the add-on randomly started working again. I'm not sure what happened.

**Comment by xavier150** [comment]
That weird, if you find how reproduct it don't hesitate to tell me

Le lun. 20 juil. 2020 à 11:20, HeyNinety <notifications@github.com> a
écrit :

**Comment by TriPunk** [comment]
Hello, I am having a similar issue with 2.83 and UE4 4.25.  Unfortunately, I do not get an error my unreal just crash a split second after "importing assets" pops up.

**Comment by xavier150** [comment]
Hello @TriPunk That seem be a different issue, you can cread a new git issue and send me the Blender file? I will try on my side.

**Comment by TriPunk** [comment]
Hello, @xavier150  thank you for the quick reply. I discovered that it was a user error on my end. iv removed my previous comment to avoid future confusion.

**Comment by JamesTroici** [comment]
I'm having this issue as well. this is the error I'm getting. I disabled the fbx addon in case that was causing issues but still no luck.

Traceback (most recent call last):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\operators.py", line 15, in execute
    export.send2ue(properties)
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 954, in send2ue
    if validate(properties):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 926, in validate
    if not validations.validate_unreal_skeleton_path(unreal, properties):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\validations.py", line 234, in validate_unreal_skeleton_path
    if not unreal.asset_exists(properties.unreal_skeleton_asset_path):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\unreal.py", line 140, in asset_exists
    return bool(unreal_response['success'])
TypeError: string indices must be integers

location: <unknown location>:-1

bpy.data.window_managers["WinMan"].addon_search = "fbx"
Traceback (most recent call last):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\operators.py", line 15, in execute
    export.send2ue(properties)
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 954, in send2ue
    if validate(properties):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 926, in validate
    if not validations.validate_unreal_skeleton_path(unreal, properties):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\validations.py", line 234, in validate_unreal_skeleton_path
    if not unreal.asset_exists(properties.unreal_skeleton_asset_path):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\unreal.py", line 140, in asset_exists
    return bool(unreal_response['success'])
TypeError: string indices must be integers

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\operators.py", line 15, in execute
    export.send2ue(properties)
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 954, in send2ue
    if validate(properties):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 926, in validate
    if not validations.validate_unreal_skeleton_path(unreal, properties):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\validations.py", line 234, in validate_unreal_skeleton_path
    if not unreal.asset_exists(properties.unreal_skeleton_asset_path):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\unreal.py", line 140, in asset_exists
    return bool(unreal_response['success'])
TypeError: string indices must be integers

location: <unknown location>:-1

Fixing this would mean a lot!

**Comment by xavier150** [comment]
Hello @JamesTroici 
It looks like this error come from Send2ue Addon, that not my addon

**Comment by MasterAbsinthe** [comment]
Hi! I wanted to add to this thread for future reference. I had the same issue, and after much testing I found out that the solution is to unwrap the mesh. My object had a boolean modifier, and I also had to unwrap the boolean object. Hope this helps any such future issues.

**Comment by xavier150** [comment]
> Hi! I wanted to add to this thread for future reference. I had the same issue, and after much testing I found out that the solution is to unwrap the mesh. My object had a boolean modifier, and I also had to unwrap the boolean object. Hope this helps any such future issues.

Hello You have the same first issue or Send2ue addon issue ? If it not Send2ue you can open an new issue post on github here.
