### ISSUE TITLE
Python: Traceback (most recent call last):

### ISSUE THREAD

**Issue by akmaltong** [xavier150/Blender-For-UnrealEngine-Addons#83]
Python: Traceback (most recent call last):
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\__init__.py", line 1789, in execute
    bfu_ExportAsset.ExportForUnrealEngine()
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 226, in ExportForUnrealEngine
    PrepareAndSaveDataForExport()
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 202, in PrepareAndSaveDataForExport
    targetcollection = baseCollectionName,
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_ExportAsset.py", line 62, in ExportAllAssetByList
    ExportSingleStaticMeshCollection(originalScene, GetCollectionExportDir(), GetCollectionExportFileName(col), col)
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_ExportAssetsByType.py", line 512, in ExportSingleStaticMeshCollection
    ExportSingleStaticMesh(originalScene, dirpath, filename, obj)
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_ExportAssetsByType.py", line 539, in ExportSingleStaticMesh
    ApplyNeededModifierToSelect()
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-for-unrealengine\bfu_Utils.py", line 294, in ApplyNeededModifierToSelect
    bpy.ops.object.modifier_apply(modifier = mod.name)
  File "C:\Program Files\Blender Foundation\blender-2.92.0rc-windows64\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Ошибка: Модификатор отключён, применение не выполнено

location: <unknown location>:-1

**Comment by xavier150** [comment]
Hello @akmaltong , 
You still have this error with the last preview release? 
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases Pre Rev 0.2.8.3
If yes you can send me the file? I will try on my side.

**Comment by akmaltong** [comment]
> Здравствуйте @akmaltong ,
> У вас все еще есть эта ошибка с последним предварительным выпуском?
> https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases Pre Rev 0.2.8.3
> Если да, то вы можете прислать мне файл? Я постараюсь на своей стороне.

Python: Traceback (most recent call last):
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\keentools_facebuilder\interface\panels.py", line 83, in poll
    return _show_all_panels()
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\keentools_facebuilder\interface\panels.py", line 45, in _show_all_panels
    state, _ = what_is_state()
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\keentools_facebuilder\utils\manipulate.py", line 88, in what_is_state
    if _check_facs_available(len(obj.data.vertices)):
  File "C:\Users\akmal\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\keentools_facebuilder\utils\manipulate.py", line 49, in _check_facs_available
    return pkt.module().FacsExecutor.facs_available(count)
pykeentools.ModelLoadingException: failed to read model geometry

location: <unknown location>:-1

**Comment by akmaltong** [comment]
Здравствуйте) да такая ошибка на последней версии вашей программы(

**Comment by xavier150** [comment]
Oh look like this error come from keentools_facebuilder

**Comment by xavier150** [comment]
Hey @akmaltong I published the new [update 0.2.8](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.8) 
So I close issue, keentools_facebuilder error don't come from my addon.

**Comment by akmaltong** [comment]
> Hey @akmaltong I published the new [update 0.2.8](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.8) 
> So I close issue, keentools_facebuilder error don't come from my addon.

Hi. Shanks))))
