### ISSUE TITLE
Unable to export anything from Blender to Unreal

### ISSUE THREAD

**Issue by JamesTroici** [xavier150/Blender-For-UnrealEngine-Addons#89]
Hello, this is the error I'm getting. I disabled the fbx addon in case that was causing issues but still no luck. I also followed numerous videos to make sure I had the correct plugins turned on in Unreal and that I was exporting correctly in Blender. I tried doing this in multiple blender projects. I'm currently using 2.9.0 for blender and am up to date on Unreal.

Traceback (most recent call last):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\operators.py", line 15, in execute
export.send2ue(properties)
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 954, in send2ue
if validate(properties):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 926, in validate
if not validations.validate_unreal_skeleton_path(unreal, properties):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\validations.py", line 234, in validate_unreal_skeleton_path
if not unreal.asset_exists(properties.unreal_skeleton_asset_path):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\unreal.py", line 140, in asset_exists
return bool(unreal_response['success'])
TypeError: string indices must be integers

location: :-1

bpy.data.window_managers["WinMan"].addon_search = "fbx"
Traceback (most recent call last):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\operators.py", line 15, in execute
export.send2ue(properties)
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 954, in send2ue
if validate(properties):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 926, in validate
if not validations.validate_unreal_skeleton_path(unreal, properties):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\validations.py", line 234, in validate_unreal_skeleton_path
if not unreal.asset_exists(properties.unreal_skeleton_asset_path):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\unreal.py", line 140, in asset_exists
return bool(unreal_response['success'])
TypeError: string indices must be integers

location: :-1

Traceback (most recent call last):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\operators.py", line 15, in execute
export.send2ue(properties)
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 954, in send2ue
if validate(properties):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\export.py", line 926, in validate
if not validations.validate_unreal_skeleton_path(unreal, properties):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\validations.py", line 234, in validate_unreal_skeleton_path
if not unreal.asset_exists(properties.unreal_skeleton_asset_path):
File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\send2ue\functions\unreal.py", line 140, in asset_exists
return bool(unreal_response['success'])
TypeError: string indices must be integers

location: :-1

Fixing this would mean a lot!

**Comment by xavier150** [comment]
Hey @JamesTroici !

I'm sorry but this error come from send2ue addon, that not my addon and I don't have control on it :/
My addon is Blender-For-UnrealEngine: https://youtu.be/YLOZZIlhgaM
You can download [here](https://github.com/xavier150/Blender-For-UnrealEngine-Addons) if you want try:  :p
