### ISSUE TITLE
Error when exporting skeletal mesh with NLA animation

### ISSUE THREAD

**Issue by zxnny** [xavier150/Blender-For-UnrealEngine-Addons#98]
I'm on Blender 2.93 and I'm using the latest pre-release of the addon (0.2.9.2) but also tried 0.2.8, getting the same error with that. I have a character with a Mixamo rig with 2 actions in the NLA editor. When selecting "Not exported" under "Action to export" it does it without any errors but when I import into UE4 there's no animation. When selecting "Export specific list" or "Export auto" I get the following error message:

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2285, in execute
    bfu_export_asset.ExportForUnrealEngine()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 320, in ExportForUnrealEngine
    ExportAllAssetByList(
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 240, in ExportAllAssetByList
    ProcessActionExport(obj, action)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_export_single_fbx_action.py", line 55, in ProcessActionExport
    ExportSingleFbxAction(scene, dirpath, GetActionExportFileName(obj, action), obj, action)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_export_single_fbx_action.py", line 176, in ExportSingleFbxAction
    OriginalActionName = active.animation_data.action.name
AttributeError: 'NoneType' object has no attribute 'action'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2285, in execute
    bfu_export_asset.ExportForUnrealEngine()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 320, in ExportForUnrealEngine
    ExportAllAssetByList(
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_export_asset.py", line 240, in ExportAllAssetByList
    ProcessActionExport(obj, action)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_export_single_fbx_action.py", line 55, in ProcessActionExport
    ExportSingleFbxAction(scene, dirpath, GetActionExportFileName(obj, action), obj, action)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_export_single_fbx_action.py", line 176, in ExportSingleFbxAction
    OriginalActionName = active.animation_data.action.name
AttributeError: 'NoneType' object has no attribute 'action'

location: <unknown location>:-1

Unless you have an idea as to why I'm getting this error I'd gladly send over my .blend file for you to have a look at.

**Comment by xavier150** [comment]
Hey @zxnny ,
This error has fixed for the next release. Try the Pre-release and tell me if you still have the issue. https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.2.9.2

I will publish the new release very soon. ^^

**Comment by zxnny** [comment]
Thanks for the reply! @xavier150
Though, like I said at the top of my post, I'm already using the latest pre-release. Still getting this error.

**Comment by xavier150** [comment]
Hey Zxnny,
I'm sorry, I confused with another error.
You can send me the file? I will try to reproduce on my side.
***@***.***

**Comment by zxnny** [comment]
It's alright! I just sent it to you.

**Comment by xavier150** [comment]
Hey @zxnny !
I do a new Pre-release, you can try this one ?
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.2.9.3

**Comment by zxnny** [comment]
I tried it and it works now, thanks! Just one question though, when I import the NLA animation into Unreal its position is at the world origin (0,0,0) and not where it was in Blender. For example, in Blender, my character is walking around inside a room far into the map (28.4665, 15.2109, -2.0102 to be exact) but after importing into Unreal he's zeroed out, not in the room anymore. So, I would have to manually place him in the correct position again, which is a lot of work. Is there a way around this? I'm sure it's not supposed to be like that. Hopefully you know what I mean.

**Comment by xavier150** [comment]
@zxnny sadly that not possible. I tested and added new options for export the armature with position in the scene. 
https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch
That work for export but that don't work at the import. It is a constraint of Unreal Engine which will ignore the position of the skeleton at the import. 

![image](https://user-images.githubusercontent.com/7216958/122659667-83a86a80-d17a-11eb-8031-116d3e9f1db8.png)

If the armature position is not animated you can manualy import it with and offset in Unreal Engine. Or edit the import transform values and reimport. 
Copy the position From Blender and multiply X*100, Y*-100, Z*100

![image](https://user-images.githubusercontent.com/7216958/122677384-5f807400-d1e2-11eb-8f2b-24e0512253e1.png)


The best is doing the offset in Blender with the animation, keep the armature at location 0,0,0 and wont animation the armature location.

**Comment by zxnny** [comment]
Ah, okay. Good to know. I'm closing the issue now since my initial problem has been solved! :)
